- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-python3-xena-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
